### ISSUE TITLE
on_duplicate_key_update support?

### ISSUE THREAD

**Issue by security-intel** [benchling/sqlalchemy_batch_inserts#1]
Hello there,

Really nice feature here! Thank you. Is there any support for the on_duplicate_key_update option in the insert statement? For this batch processing mode? Thank you

**Comment by vineetgopal** [comment]
Hi @slv008, sorry for the delay in getting back to you here.

I believe the answer unfortunately is no. This module doesn't actually change any fundamental SQLAlchemy logic on how inserts are done – it simply just populates primary keys beforehand so SQLAlchemy can use it's existing fast-insert logic. It unfortunately doesn't provide any additional abilities on the inserts themselves.

Let me know if that makes sense, or if there's anything else I can help look into.
